# Autogenerated by devscripts/update-version.py

__version__ = '2026.03.11.022155'

RELEASE_GIT_HEAD = '2739baa894bb5fd826300aca8e5da626e6016380'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'Lonely233233/yt-dlp'

ORIGIN = 'Lonely233233/yt-dlp'

_pkg_version = '2026.03.11.022155'
