# Autogenerated by devscripts/update-version.py

__version__ = '2026.03.28.085309'

RELEASE_GIT_HEAD = 'c4a9396ba245c6d90538570846fd1242e76b208a'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'Lonely233233/yt-dlp'

ORIGIN = 'Lonely233233/yt-dlp'

_pkg_version = '2026.03.28.085309'
