# Autogenerated by devscripts/update-version.py

__version__ = '2026.03.23.104932'

RELEASE_GIT_HEAD = '8f7b6afef3bf25f66039ea6acd80eee17295c87f'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'Lonely233233/yt-dlp'

ORIGIN = 'Lonely233233/yt-dlp'

_pkg_version = '2026.03.23.104932'
